const flashcards = [
    { spanish: "hacer", english: "to do" },
    { spanish: "estar", english: "to be" },
    { spanish: "poder", english: "to be able to" },
    { spanish: "decir", english: "to say" },
    { spanish: "ir", english: "to go" },
    { spanish: "ver", english: "to see" },
    { spanish: "querer", english: "to want" },
    { spanish: "poner", english: "to put" },
    { spanish: "saber", english: "to know" },
    { spanish: "tener", english: "to have" },
    { spanish: "haber", english: "to have" },
    { spanish: "venir", english: "to come" },
    { spanish: "buscar", english: "to look for" },
    { spanish: "sentir", english: "to feel" },
    { spanish: "pensar", english: "to think" },
    { spanish: "encontrar", english: "to find" },
    { spanish: "trabajar", english: "to work" },
    { spanish: "creer", english: "to believe" },
    { spanish: "volver", english: "to return" },
    { spanish: "amar", english: "to love" },
    { spanish: "necesitar", english: "to need" },
    { spanish: "hablar", english: "to speak" },
    { spanish: "llevar", english: "to take" },
    { spanish: "deber", english: "to owe" },
    { spanish: "dejar", english: "to leave" },
    { spanish: "sentarse", english: "to sit down" },
    { spanish: "comer", english: "to eat" },
    { spanish: "tomar", english: "to take" },
    { spanish: "poder", english: "to be able to" },
    { spanish: "vivir", english: "to live" },
    { spanish: "entender", english: "to understand" },
    { spanish: "empezar", english: "to start" },
    { spanish: "dar", english: "to give" },
    { spanish: "conocer", english: "to know" },
    { spanish: "querer", english: "to want" },
    { spanish: "seguir", english: "to follow" },
    { spanish: "ayudar", english: "to help" },
    { spanish: "pasar", english: "to happen" },
    { spanish: "esperar", english: "to wait" },
    { spanish: "decir", english: "to say" },
    { spanish: "quedar", english: "to stay" },
    { spanish: "mirar", english: "to look" },
    { spanish: "venir", english: "to come" },
    { spanish: "gustar", english: "to like" },
    { spanish: "creer", english: "to believe" },
    { spanish: "dejar", english: "to let" },
    { spanish: "probar", english: "to try" },
    { spanish: "soler", english: "to usually" },
    { spanish: "servir", english: "to serve" },
    { spanish: "tratar", english: "to try" },
    { spanish: "nacer", english: "to be born" },
    { spanish: "comprar", english: "to buy" },
    { spanish: "deber", english: "to must" },
    { spanish: "sentir", english: "to regret" },
    { spanish: "recibir", english: "to receive" },
    { spanish: "pensar", english: "to plan" },
    { spanish: "sonar", english: "to sound" },
    { spanish: "querer", english: "to wish" },
    { spanish: "sonar", english: "to dream" },
    { spanish: "seguir", english: "to continue" },
    { spanish: "salir", english: "to go out" },
    { spanish: "volver", english: "to return" },
    { spanish: "esperar", english: "to hope" },
    { spanish: "llevar", english: "to carry" },
    { spanish: "cerrar", english: "to close" },
    { spanish: "ocurrir", english: "to occur" },
    { spanish: "leer", english: "to read" },
    { spanish: "contar", english: "to count" },
    { spanish: "caer", english: "to fall" },
    { spanish: "cambiar", english: "to change" },
    { spanish: "volver", english: "to turn" },
    { spanish: "conocer", english: "to meet" },
    { spanish: "subir", english: "to go up" },
    { spanish: "sacar", english: "to take out" },
    { spanish: "mantener", english: "to keep" },
    { spanish: "andar", english: "to walk" },
    { spanish: "tratar", english: "to treat" },
    { spanish: "morir", english: "to die" },
    { spanish: "explicar", english: "to explain" },
    { spanish: "caer", english: "to drop" },
    { spanish: "encontrar", english: "to encounter" },
    { spanish: "realizar", english: "to realize" },
    { spanish: "dejar", english: "to quit" },
    { spanish: "encontrar", english: "to locate" },
    { spanish: "empezar", english: "to begin" },
    { spanish: "recordar", english: "to remember" },
    { spanish: "hablar", english: "to talk" },
    { spanish: "esperar", english: "to expect" },
    { spanish: "hacer", english: "to make" },
    { spanish: "conseguir", english: "to get" },
    { spanish: "deber", english: "to owe" },
    { spanish: "llevar", english: "to wear
